/** CONSULTAS BASICAS DE LAS 5 TABLAS AGREGADAS **/

SELECT *
FROM DIM_CALENDAR

SELECT *
FROM DIM_CATEGORY

SELECT *
FROM DIM_PRODUCT

SELECT * 
FROM DIM_SEGMENT

SELECT *
FROM FACT_SALES

/** CONSULTA PARA VERIFICAR LAS VENTAS POR MONTO **/

SELECT	Fecha,
		WEEK,
		ITEM_CODE,
		REGION,
		TOTAL_VALUE_SALES
FROM dbo.FACT_SALES
	INNER JOIN DIM_CALENDAR ON DIM_CALENDAR.Semana = FACT_SALES.WEEK
ORDER BY TOTAL_VALUE_SALES DESC;

/** CONSULTA PARA VERIFICAR LAS VENTAS POR FECHA **/

SELECT	Fecha,
		WEEK,
		ITEM_CODE,
		REGION,
		TOTAL_VALUE_SALES
FROM dbo.FACT_SALES
	INNER JOIN DIM_CALENDAR ON DIM_CALENDAR.Semana = FACT_SALES.WEEK
ORDER BY Fecha ASC;